# Generated by Django 2.2.27 on 2022-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmenGunea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filma',
            name='bozkak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filma',
            name='urtea',
            field=models.IntegerField(),
        ),
    ]
